sudo: required

services:
  # we need to tell travis that we want to use docker
  - docker

before_install:
  # build development image
  # note that we used ./client as build context
  - docker build -f ./client/Dockerfile.dev -t docker-react-travis ./client

script:
  # -e CI=true to show result and exit
  - docker run -e CI=true docker-react-travis npm run test

after_success:
  - docker build -t hatemabushaala1998/multi-client ./client
  - docker build -t hatemabushaala1998/multi-server ./server
  - docker build -t hatemabushaala1998/multi-worker ./worker
  - docker build -t hatemabushaala1998/multi-nginx ./nginx
  # push images to docker-hub
  # get email and password from travis env
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  # push to docker
  - docker push hatemabushaala1998/multi-client
  - docker push hatemabushaala1998/multi-server
  - docker push hatemabushaala1998/multi-worker
  - docker push hatemabushaala1998/multi-nginx
  - echo "push done to docker"
