version: "3"
services:
  nginx:
    restart: always
    build:
      context: ./nginx
      dockerfile: Dockerfile
    ports:
      - "80:80"

  postgres:
    image: "postgres:latest"
    environment:
      - POSTGRES_PASSWORD=postgres_password
  redis:
    image: "redis"
  api:
    build:
      context: ./server
      dockerfile: Dockerfile
    # setup node env
    environment:
      # similar to redis service name (as u name it)
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      # similar to pg service name (as u name it)
      - PGHOST=postgres
      - PGUSER=postgres
      - PGDATABASE=postgres
      - PGPASSWORD=postgres_password
      - PGPORT=5432
    # ports:
    #   - "8000:8000"

  worker:
    build:
      dockerfile: Dockerfile
      context: ./worker
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379

  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    # ports:
    #   - "3000:3000"
